### ISSUE TITLE
Take an associative array to allow mapping file extensions to lexer names

### ISSUE THREAD

**Issue by Gittenburg** [Gittenburg/SyntaxHighlightPages#1]
It would work like:

```
$wgSyntaxHighlightPagesSuffixes = ["htm" => "html"];
```

**Comment by himanshu007-creator** [comment]
i would like to work on this issue. Please guide me further

**Comment by Gittenburg** [comment]
Currently the extension is configured like:

    $wgSyntaxHighlightPagesSuffixes = ['html', 'css', 'xml', 'js', 'php'];

With the limitation that the suffixes need to be a short name listed under https://pygments.org/docs/lexers/.

This issue is about letting the user map specific file extensions to specific lexer names as requested in https://www.mediawiki.org/w/index.php?title=Topic:W5639wrl5o3fw5t8.

I unfortunately don't have time to guide you regarding the implementation of this feature, I just labeled this as `good first issue` because it's a very simple issue. If you however manage to implement it and open a PR I'll review it.

**Comment by Gittenburg** [comment]
Implemented by #2.
